### PR TITLE
fixed import in example

### PR DESCRIPTION
**Pull request by Br3nda**

### CODE REVIEW

**Comment by Br3nda** [comment]
tbh i couldn't get this library to work

**Comment by Br3nda** [comment]
it's been three months without a reply, so closing this. Open the PR again if you want the patch.

**Comment by cbrand** [comment]
My appologies. It seems that the two PRs of you fell through the cracks.

Thanks for your contribution!

**Comment by cbrand** [comment]
> tbh i couldn't get this library to work

I haven't touched the code base for this in 5 years and as you've seen with your two PRs it seems that it hasn't been utilized massively either. Can you paste the example you were struggling with? Maybe I can help getting it to run and fix something on the way.

**Pull request merged**
